[package]
name = "anglerkit"
version = "0.0.0"
description = "In-development function hooking/detouring library"
edition = "2021"
authors = ["William Tremblay <tremwil@users.noreply.github.com>"]
keywords = ["detour", "hooking", "modding", "hacking", "instrumentation"]
categories = ["security", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tremwil/anglerkit"

[features]
default = ["std", "default_alloc"]
std = ["dep:region"]
block_alloc = ["dep:talc"]
default_alloc = ["std", "block_alloc"]

unstable = [
    "closure-ffi/unstable", 
    "closure-ffi/tuple_trait", 
    "closure-ffi/c_variadic",
    "talc/allocator",
    "talc/nightly_api"
]

[dependencies]
thiserror = "2.0"
closure-ffi = { version = "2.4.0", default-features = false }
talc = { version = "4.4.2", default-features = false, features = ["lock_api"], optional = true }
lock_api = "0.4.13"
clear-cache = "0.1.1"
region = { version = "3.0.2", optional = true }

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))'.dependencies]
iced-x86 = "1.21"

[target.'cfg(any(target_arch = "aarch64", target_arch = "arm"))'.dependencies]
yaxpeax-arm = "0.3.1"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]