[package]
name = "anglerkit"
version = "0.0.0"
description = "In-development function hooking/detouring library"
edition = "2024"
authors = ["William Tremblay <tremwil@users.noreply.github.com>"]
keywords = ["detour", "hooking", "modding", "hacking", "instrumentation"]
categories = ["security", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tremwil/anglerkit"

[features]
default = ["std", "default_alloc"]
std = [
    "dep:region",
    "dep:microseh",
    "dep:libc",
    "dep:setjmp"
]
block_alloc = ["dep:talc"]
default_alloc = [
    "std", 
    "block_alloc", 
    "dep:parking_lot",
    "closure-ffi/default_jit_alloc"
]

nightly = [
    "closure-ffi/unstable", 
    "closure-ffi/tuple_trait", 
    "closure-ffi/c_variadic",
    "talc/allocator",
    "talc/nightly_api"
]

[dependencies]
thiserror = "2.0"
closure-ffi = { version = "4.1.0", default-features = false, features = ["global_jit_alloc", "proc_macros"] }
talc = { version = "4.4.2", default-features = false, features = ["lock_api"], optional = true }
lock_api = "0.4.13"
parking_lot = { version = "0.12", optional = true }
spin = { version = "0.10", features = ["lock_api"] }
bitflags = "2.9.4"

clear-cache = "0.1.1"
region = { version = "3.0.2", optional = true }

[target.'cfg(target_env = "msvc")'.dependencies]
microseh = { version = "1.1.2", default-features = false, optional = true}

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", default-features = false, optional = true }
setjmp = { version = "0.1.4", optional = true }

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.61"
features = [
    "Win32_System_Kernel",
    "Win32_System_Memory",
    "Win32_System_SystemInformation",
    "Win32_System_Diagnostics_Debug"    
]

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))'.dependencies]
iced-x86 = "1.21"

[target.'cfg(any(target_arch = "aarch64", target_arch = "arm"))'.dependencies]
yaxpeax-arm = "0.3.1"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
